version: "3.8"
networks:
  django-microservices:
    external: true
services:
  # ---------------------------------------------------------------------------
  # container services
  # ---------------------------------------------------------------------------
  backend_for_frontend_ms:
    image: diegoug/backend_for_frontend_ms_dev
    container_name: backend_for_frontend_ms
    command: /bin/sh -c "python manage.py runserver 0.0.0.0:${BACKEND_FOR_FRONTEND_MS_PORT}"
    volumes:
      - ../../services/backend_for_frontend_ms:/opt/app
      - ../../common/profiles:/opt/app/profiles
      - ${LOCAL_SSH}/.ssh/id_rsa.pub:/tmp/authorized_keys:ro
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DEBUG=${DEBUG}
      - TEMPLATE_DEBUG=${TEMPLATE_DEBUG}
      - DJANGO_MICROSERVICES_KEY=${DJANGO_MICROSERVICES_KEY}
      - POSTGRES_USER_MS_DATABASE_NAME=${POSTGRES_USER_MS_DATABASE_NAME}
      - POSTGRES_USER_MS_USER=${POSTGRES_USER_MS_USER}
      - POSTGRES_USER_MS_PASSWORD=${POSTGRES_USER_MS_PASSWORD}
      - POSTGRES_USER_MS_HOST=${POSTGRES_USER_MS_HOST}
      - USER_MS_HOST=http://${USER_MS_HOST}:${USER_MS_PORT}
      - ORCHESTATOR_MS_HOST=http://${ORCHESTATOR_MS_HOST}:${ORCHESTATOR_MS_PORT}
    ports:
      - ${BACKEND_FOR_FRONTEND_MS_PORT}:${BACKEND_FOR_FRONTEND_MS_PORT}
      - ${BACKEND_FOR_FRONTEND_MS_SSH}:22
    depends_on:
      - postgres_user_ms
    networks:
      django-microservices:
        aliases:
          - ${BACKEND_FOR_FRONTEND_MS_HOST}
  orchestrator_ms:
    image: diegoug/orchestrator_ms_dev
    container_name: orchestrator_ms
    command: /bin/sh -c "python manage.py runserver 0.0.0.0:${ORCHESTATOR_MS_PORT}"
    volumes:
      - ../../services/orchestrator_ms:/opt/app
      - ../../common/profiles:/opt/app/profiles
      - ${LOCAL_SSH}/.ssh/id_rsa.pub:/tmp/authorized_keys:ro
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DEBUG=${DEBUG}
      - TEMPLATE_DEBUG=${TEMPLATE_DEBUG}
      - ORCHESTATOR_MS_HOST=${ORCHESTATOR_MS_HOST}
      - DJANGO_MICROSERVICES_KEY=${DJANGO_MICROSERVICES_KEY}
      - POSTGRES_USER_MS_DATABASE_NAME=${POSTGRES_USER_MS_DATABASE_NAME}
      - POSTGRES_USER_MS_USER=${POSTGRES_USER_MS_USER}
      - POSTGRES_USER_MS_PASSWORD=${POSTGRES_USER_MS_PASSWORD}
      - POSTGRES_USER_MS_HOST=${POSTGRES_USER_MS_HOST}
    networks:
      django-microservices:
        aliases:
          - ${ORCHESTATOR_MS_HOST}
  # author_ms_dev:
  #   image: diegoug/author_ms_dev
  #   container_name: author_ms_dev
  #   volumes:
  #     - ../../services/orchestrator_ms:/opt/app
  #     - ${LOCAL_SSH}/.ssh/id_rsa.pub:/tmp/authorized_keys:ro
  #   networks:
  #     django-microservices:
  #       aliases:
  #         - ${AUTHOR_MS_HOST}
  # book_ms_dev:
  #   image: diegoug/book_ms_dev
  #   container_name: book_ms_dev
  #   command: /bin/sh -c "while true; do echo hello world; sleep 1; done"
  #   volumes:
  #     - ../../services/book_ms:/opt/app
  #     - ${LOCAL_SSH}/.ssh/id_rsa.pub:/tmp/authorized_keys:ro
  #   networks:
  #     django-microservices:
  #       aliases:
  #         - ${BOOK_MS_HOST}
  user_ms:
    image: diegoug/user_ms_dev
    container_name: user_ms
    command: /bin/sh -c "python manage.py runserver 0.0.0.0:${USER_MS_PORT}"
    volumes:
      - ../../services/user_ms:/opt/app
      - ../../common/profiles:/opt/app/profiles
      - ${LOCAL_SSH}/.ssh/id_rsa.pub:/tmp/authorized_keys:ro
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DEBUG=${DEBUG}
      - TEMPLATE_DEBUG=${TEMPLATE_DEBUG}
      - DJANGO_MICROSERVICES_KEY=${DJANGO_MICROSERVICES_KEY}
      - USER_MS_HOST=${USER_MS_HOST}
      - POSTGRES_USER_MS_DATABASE_NAME=${POSTGRES_USER_MS_DATABASE_NAME}
      - POSTGRES_USER_MS_USER=${POSTGRES_USER_MS_USER}
      - POSTGRES_USER_MS_PASSWORD=${POSTGRES_USER_MS_PASSWORD}
      - POSTGRES_USER_MS_HOST=${POSTGRES_USER_MS_HOST}
      - BACKEND_FOR_FRONTEND_MS_HOST=${BACKEND_FOR_FRONTEND_MS_HOST}
      - ORCHESTATOR_MS_HOST=${ORCHESTATOR_MS_HOST}
    ports:
      - ${USER_MS_PORT}:${USER_MS_PORT}
      - ${USER_MS_SSH}:22
    depends_on:
     - postgres_user_ms
    networks:
      django-microservices:
        aliases:
          - ${USER_MS_HOST}
  # ---------------------------------------------------------------------------
  # container services
  # ---------------------------------------------------------------------------
  # postgres user ms
  postgres_user_ms:
    image: postgres:14.1
    container_name: postgres_user_ms
    ports:
      - ${POSTGRES_USER_MS_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_USER_MS_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER_MS_USER}
      - POSTGRES_DB=${POSTGRES_USER_MS_DATABASE_NAME}
    volumes:
      - ${LOCAL_VAR}/lib/postgres_user_ms:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_MS_USER} -d ${POSTGRES_USER_MS_DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      django-microservices:
        aliases:
          - ${POSTGRES_USER_MS_HOST}
